package org.beobma.classWarPlugin.keyword

enum class Keyword(val string: String) {
    Arrow("<gold><bold>화살</bold><gray>"),
    Invalidity("<dark_gray><bold>무효</bold><gray>"),
    Stealth("<light_purple><bold>은신</bold><gray>"),
    Mana("<blue><bold>마나</bold><gray>"),
    Burn("<red><bold>화상</bold><gray>"),
    Shield("<aqua><bold>보호막</bold><gray>"),
    TrueDamage("<white><bold>고정 피해</bold><gray>"),
    Vibration("<gold><bold>진동</bold><gray>"),
    VibrationExplosion("<gold><bold>진동 폭발</bold><gray>"),
    AbnormalStatusDamage("<green><bold>상태이상 피해</bold><gray>"),
    Gravity("<gold><bold>중력</bold>gray>"),
    SpecialVictoryCard("<yellow><bold>특수승리 카드</bold><gray>"),
    Untargetability("<dark_gray><bold>대상 지정 불가</bold><gray>"),
    Abyss("<black><bold>심연</bold><gray>"),
    Silence("<dark_gray><bold>침묵</bold><gray>"),
    Exile("<dark_gray><bold>추방</bold><gray>"),
    Bleeding("<dark_red><bold>출혈</bold><gray>"),
    RespiteHealth("<dark_red><bold>유예체력</bold><gray>"),
    Execution("<dark_red><bold>처형</bold><gray>"),
    Electrocution("<light_purple><bold>감전</bold><gray>"),
    Stun("<yellow><bold>기절</bold><gray>"),
    Snare("<dark_gray><bold>속박</bold><gray>"),
    Brightness("<white><bold>광휘</bold><gray>"),
    Charge("<blue><bold>충전</bold><gray>"),
    Fix("<dark_gray><bold>고정</bold><gray>"),
    Frostbite("<dark_blue><bold>동상</bold><gray>"),
    Freezing("<white><bold>빙결</bold><gray>")
}