package org.beobma.classWarPlugin.ability

import org.beobma.classWarPlugin.gameClass.GameClass
import org.beobma.classWarPlugin.gameClass.list.*
import org.beobma.classWarPlugin.gameClass.list.Error
import org.beobma.classWarPlugin.gameClass.list.dummy.Dummy

/** Stable IDs are the persistence contract; constructor names remain an implementation detail. */
object AbilityCatalog {
    private val factories: Map<String, () -> GameClass> = mapOf(
        "abyssal-veil" to ::AbyssalVeil,
        "anchor" to ::Anchor,
        "area-development" to ::AreaDevelopment,
        "assassin" to ::Assassin,
        "astronomer" to ::Astronomer,
        "avenger" to ::Avenger,
        "back-room" to ::BackRoom,
        "barrier" to ::Barrier,
        "berserker" to ::Berserker,
        "blacksmith" to ::Blacksmith,
        "brave" to ::Brave,
        "bull" to ::Bull,
        "chameleon" to ::Chameleon,
        "charger" to ::Charger,
        "chubby" to ::Chubby,
        "con-artist" to ::ConArtist,
        "conflict" to ::Conflict,
        "contractor" to ::Contractor,
        "damocles" to ::Damocles,
        "darkness" to ::Darkness,
        "death-note" to ::DeathNote,
        "devastating-blow" to ::DevastatingBlow,
        "duelist" to ::Duelist,
        "dummy" to ::Dummy,
        "dwarf" to ::Dwarf,
        "elementalist" to ::Elementalist,
        "error" to ::Error,
        "exodia" to ::Exodia,
        "fear" to ::Fear,
        "feather" to ::Feather,
        "gambler" to ::Gambler,
        "general-person" to ::GeneralPerson,
        "geometer" to ::Geometer,
        "ghost" to ::Ghost,
        "grass" to ::Grass,
        "grave-robber" to ::GraveRobber,
        "gun-blader" to ::GunBlader,
        "hacker" to ::Hacker,
        "hero" to ::Hero,
        "hide-and-seek" to ::HideAndSeek,
        "high-jumper" to ::HighJumper,
        "hikikomori" to ::Hikikomori,
        "ice-wizard" to ::IceWizard,
        "jupiter" to ::Jupiter,
        "just-light" to ::JustLight,
        "knight" to ::Knight,
        "land-wizard" to ::LandWizard,
        "levatain" to ::Levatain,
        "light-wizard" to ::LightWizard,
        "lightning-wizard" to ::LightningWizard,
        "lucky-one" to ::LuckyOne,
        "luna" to ::Luna,
        "mars" to ::Mars,
        "mathematician" to ::Mathematician,
        "mercurius" to ::Mercurius,
        "meteor" to ::Meteor,
        "neptune" to ::Neptune,
        "pacifist" to ::Pacifist,
        "parasite" to ::Parasite,
        "pat-and-matt" to ::PatAndMatt,
        "peanuts" to ::Peanuts,
        "phantom" to ::Phantom,
        "pluto" to ::Pluto,
        "portal-gun" to ::PortalGun,
        "rainbow-bridge" to ::RainbowBridge,
        "referee" to ::Referee,
        "refugees" to ::Refugees,
        "reverse" to ::Reverse,
        "roulette" to ::Roulette,
        "sagittarius" to ::Sagittarius,
        "saturnus" to ::Saturnus,
        "shy-person" to ::ShyPerson,
        "sniper" to ::Sniper,
        "sol" to ::Sol,
        "solar-system" to ::SolarSystem,
        "spider-man" to ::SpiderMan,
        "stalker" to ::Stalker,
        "swordplay" to ::Swordplay,
        "terra" to ::Terra,
        "terrorist" to ::Terrorist,
        "thunderclap-flash" to ::ThunderclapFlash,
        "time-maniqulator" to ::TimeManiqulator,
        "tonic" to ::Tonic,
        "tour" to ::Tour,
        "train" to ::Train,
        "train-carriage" to ::TrainCarriage,
        "trapper" to ::Trapper,
        "uranus" to ::Uranus,
        "vampire" to ::Vampire,
        "venus" to ::Venus,
        "warlock" to ::Warlock,
        "watchmaker" to ::Watchmaker,
        "weapon-master" to ::WeaponMaster,
        "wounds-wind" to ::WoundsWind,
    )
    private val enabledIds = listOf(
        "berserker", "sniper", "meteor", "time-maniqulator", "land-wizard",
        "gambler", "knight", "lightning-wizard", "light-wizard", "abyssal-veil",
        "warlock", "geometer", "duelist", "astronomer", "assassin",
        "ice-wizard", "gun-blader", "watchmaker", "barrier", "darkness",
        "feather", "general-person", "grave-robber", "hacker", "spider-man",
        "trapper", "mathematician", "portal-gun", "tour", "pacifist",
        "roulette", "area-development", "parasite", "chubby", "vampire",
        "contractor", "levatain", "weapon-master", "death-note", "swordplay",
        "anchor", "avenger", "bull", "con-artist", "conflict",
        "damocles", "devastating-blow", "error", "exodia", "ghost",
        "grass", "hero", "high-jumper", "hikikomori", "phantom",
        "refugees", "stalker", "tonic", "chameleon", "dwarf",
        "just-light", "lucky-one", "pat-and-matt", "peanuts", "rainbow-bridge",
        "reverse", "sagittarius", "shy-person", "terrorist", "thunderclap-flash",
        "train", "train-carriage", "wounds-wind", "blacksmith", "brave",
        "charger", "elementalist", "solar-system", "sol", "luna",
        "mercurius", "venus", "terra", "mars", "jupiter",
        "saturnus", "uranus", "neptune", "pluto",
    )
    fun create(id: String): GameClass = requireNotNull(factories[id]) { "Unknown class ID: $id" }.invoke()
    fun enabledClasses(): List<GameClass> = enabledIds.map(::create)
}
